<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Forces NuGet to use PackageReference resolution properly under .NET 4.8 -->
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
